version: "3.8"

services:
  db:
    image: mariadb:lts
    # volumes:
    #   - db-store:/var/lib/mysql
    # platform: linux/amd64
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=mnts

  backend-app:
    image: alvaniev/mnts-backend
    container_name: mnts-backend
    # volumes:
    #   - static-dir:/usr/src/app/public
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - NODE_DBDIALECT=mysql
      - NODE_DBHOST=db
      - NODE_DBPORT=3306
      - NODE_DBUSER=root
      - NODE_DBPWD=root
      - NODE_DBSCHEMA=mnts
      - NODE_DBSYNC=true
      - NODE_HOST=http://localhost:3000

# volumes:
#   db-store:
#     name: db-store
#   static-dir:
#     name: mnts-static-dir