version: "3.8"

services:
  backend:
    image: alvaniev/mnts-backend
    container_name: mnts-backend
    ports:
      - 3000:3000
    environment:
      - NODE_DBDIALECT=mysql
      - NODE_DBHOST=db
      - NODE_DBPORT=3306
      - NODE_DBUSER=root
      - NODE_DBPWD=root
      - NODE_DBSCHEMA=mnts
      - NODE_DBSYNC=true
      - NODE_HOST=http://localhost:3000
