version: "3.8"

services:  
  db:
    image: mariadb:lts
    # volumes:
    #   - db-store:/var/lib/mysql
    # platform: linux/amd64
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=mnts

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8087:8080   

# volumes:
#   db-store:
#     name: db-store